version: '3'

services:

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks: 
      - mynet

  mssql:
    build:
      context: .
      dockerfile: Dockerfile-MSSQL
    restart: always
    ports:
      - '1433:1433'
    env_file:
      - .env
    networks: 
      - mynet

  web:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks: 
      - mynet

networks: 
  mynet:
